export type TestType = 'vocabulary' | 'grammar' | 'mixed' | 'full';

export interface Question {
  id: number;
  category: 'vocabulary' | 'grammar';
  question: string;
  options: string[];
  correctIndex: number;
  /**
   * The lesson this question was generated from. Only set by the scoped
   * "test out of a lesson range" generator (`generateLessonRangeQuestions`)
   * below — the full-language proficiency test generated by
   * `generateTestQuestions` samples across every lesson and has no single
   * lesson to attribute a question to, so it leaves this unset.
   */
  lessonId?: string;
}

interface VocabWord {
  word: string;
  reading: string;
  meaning: string;
  example: string;
  exampleMeaning: string;
}

interface VocabLesson {
  id: string;
  words: VocabWord[];
  exercises: Array<{
    type: string;
    items?: Array<{ sentence: string; answer: string; hint: string }>;
  }>;
}

interface GrammarQuiz {
  type: string;
  question: string;
  options: string[];
  answer: number;
}

const QUESTION_COUNTS: Record<TestType, { vocab: number; grammar: number }> = {
  vocabulary: { vocab: 15, grammar: 0 },
  grammar: { vocab: 0, grammar: 15 },
  mixed: { vocab: 10, grammar: 10 },
  full: { vocab: 20, grammar: 20 },
};

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function pickRandom<T>(arr: T[], n: number): T[] {
  return shuffle(arr).slice(0, n);
}

function pickDistractors(correct: string, pool: string[], count: number): string[] {
  const filtered = pool.filter((w) => w !== correct);
  return pickRandom(filtered, count);
}

async function fetchVocabLessons(lang: string): Promise<VocabLesson[]> {
  const base = import.meta.env.BASE_URL;
  try {
    const indexRes = await fetch(`${base}content/vocab/${lang}/index.json`);
    if (!indexRes.ok) return [];
    const index: { id: string }[] = await indexRes.json();
    const results = await Promise.allSettled(
      index.map(async ({ id }) => {
        const res = await fetch(`${base}content/vocab/${lang}/${id}.json`);
        if (!res.ok) return null;
        return res.json() as Promise<VocabLesson>;
      })
    );
    return results
      .filter((r): r is PromiseFulfilledResult<VocabLesson | null> => r.status === 'fulfilled')
      .map((r) => r.value)
      .filter((v): v is VocabLesson => v !== null);
  } catch {
    return [];
  }
}

async function fetchGrammarQuizzes(lang: string): Promise<GrammarQuiz[]> {
  const base = import.meta.env.BASE_URL;
  try {
    const indexRes = await fetch(`${base}content/grammar/${lang}/index.json`);
    if (!indexRes.ok) return [];
    const index: { id: string }[] = await indexRes.json();
    const quizzes: GrammarQuiz[] = [];
    const results = await Promise.allSettled(
      index.map(async ({ id }) => {
        const res = await fetch(`${base}content/grammar/${lang}/${id}.md`);
        if (!res.ok) return [];
        const text = await res.text();
        const matches = text.matchAll(/<!-- quiz:(.*?) -->/g);
        const parsed: GrammarQuiz[] = [];
        for (const m of matches) {
          try {
            parsed.push(JSON.parse(m[1]));
          } catch { /* skip malformed */ }
        }
        return parsed;
      })
    );
    for (const r of results) {
      if (r.status === 'fulfilled') quizzes.push(...r.value);
    }
    return quizzes;
  } catch {
    return [];
  }
}

function generateVocabQuestions(lessons: VocabLesson[], count: number): Question[] {
  const allWords = lessons.flatMap((l) => l.words);
  if (allWords.length < 4) return [];

  const meaningPool = allWords.map((w) => w.meaning);
  const wordPool = allWords.map((w) => w.word);
  const questions: Question[] = [];

  // Collect fill-blank items from exercises
  const fillBlanks: Array<{ sentence: string; answer: string; hint: string; lessonWords: VocabWord[] }> = [];
  for (const lesson of lessons) {
    for (const ex of lesson.exercises) {
      if (ex.type === 'fill-blank' && ex.items) {
        for (const item of ex.items) {
          fillBlanks.push({ ...item, lessonWords: lesson.words });
        }
      }
    }
  }

  const selectedWords = pickRandom(allWords, count);

  for (let i = 0; i < selectedWords.length; i++) {
    const w = selectedWords[i];
    const questionType = Math.random();

    if (questionType < 0.4) {
      // Show word → pick meaning
      const distractors = pickDistractors(w.meaning, meaningPool, 3);
      const opts = shuffle([w.meaning, ...distractors]);
      questions.push({
        id: i,
        category: 'vocabulary',
        question: `What does "${w.word}" (${w.reading}) mean?`,
        options: opts,
        correctIndex: opts.indexOf(w.meaning),
      });
    } else if (questionType < 0.8) {
      // Show meaning → pick word
      const distractors = pickDistractors(w.word, wordPool, 3);
      const opts = shuffle([w.word, ...distractors]);
      questions.push({
        id: i,
        category: 'vocabulary',
        question: `Which word means "${w.meaning}"?`,
        options: opts,
        correctIndex: opts.indexOf(w.word),
      });
    } else {
      // Fill-in-blank from exercises (fallback to meaning→word)
      const fb = fillBlanks.length > 0 ? fillBlanks.splice(Math.floor(Math.random() * fillBlanks.length), 1)[0] : null;
      if (fb) {
        const distractors = pickDistractors(fb.answer, wordPool, 3);
        const opts = shuffle([fb.answer, ...distractors]);
        questions.push({
          id: i,
          category: 'vocabulary',
          question: `Fill in the blank: ${fb.sentence} (${fb.hint})`,
          options: opts,
          correctIndex: opts.indexOf(fb.answer),
        });
      } else {
        const distractors = pickDistractors(w.word, wordPool, 3);
        const opts = shuffle([w.word, ...distractors]);
        questions.push({
          id: i,
          category: 'vocabulary',
          question: `Which word means "${w.meaning}"?`,
          options: opts,
          correctIndex: opts.indexOf(w.word),
        });
      }
    }
  }

  return questions;
}

function generateGrammarQuestions(quizzes: GrammarQuiz[], count: number): Question[] {
  const selected = pickRandom(quizzes, count);
  return selected.map((q, i) => ({
    id: 1000 + i,
    category: 'grammar' as const,
    question: q.question,
    options: q.options,
    correctIndex: q.answer,
  }));
}

export async function generateTestQuestions(lang: string, type: TestType): Promise<Question[]> {
  const counts = QUESTION_COUNTS[type];
  const questions: Question[] = [];

  if (counts.vocab > 0) {
    const lessons = await fetchVocabLessons(lang);
    questions.push(...generateVocabQuestions(lessons, counts.vocab));
  }

  if (counts.grammar > 0) {
    const quizzes = await fetchGrammarQuizzes(lang);
    questions.push(...generateGrammarQuestions(quizzes, counts.grammar));
  }

  // Re-assign IDs after combining and shuffling
  const shuffled = shuffle(questions);
  return shuffled.map((q, i) => ({ ...q, id: i }));
}

// ─── Scoped "test out of a lesson range" generation ─────────────────────────
//
// Unlike `generateTestQuestions` above (which samples across an entire
// language's content for the standalone Proficiency Tests, untouched by any
// of this), the functions below take an *explicit, ordered* list of lesson
// ids — exactly the range a learner picked to test out of — and guarantee
// two things the standalone test never needed to:
//
//   1. Every lesson id in the input either contributes at least one
//      attributed question, or is reported back as "missing" so the caller
//      can refuse the attempt instead of silently granting credit for a
//      lesson nobody was actually tested on.
//   2. Every generated question carries the `lessonId` it came from.

/** A cap so an enormous range (most of a course) can't generate an unbounded quiz. */
const MAX_RANGE_QUESTIONS = 40;

export interface LessonRangeQuestions {
  questions: Question[];
  /** Lesson ids (subset of the input, same order) that contributed a question. */
  coveredLessonIds: string[];
  /**
   * Lesson ids that could not be given an attributable question — no vocab
   * words, no quiz blocks, or (for vocab) too few distinct words anywhere in
   * the range to build multiple-choice distractors. A non-empty list here
   * means coverage cannot be guaranteed and the range should be rejected.
   */
  missingLessonIds: string[];
}

async function fetchVocabLessonsByIds(lang: string, lessonIds: readonly string[]): Promise<VocabLesson[]> {
  const base = import.meta.env.BASE_URL;
  const byId = new Map<string, VocabLesson>();
  const results = await Promise.allSettled(
    lessonIds.map(async (id) => {
      const res = await fetch(`${base}content/vocab/${lang}/${id}.json`);
      if (!res.ok) return null;
      const lesson = (await res.json()) as VocabLesson;
      return { ...lesson, id };
    })
  );
  for (const r of results) {
    if (r.status === 'fulfilled' && r.value) byId.set(r.value.id, r.value);
  }
  // Preserve input order, dropping ids whose content failed to load —
  // those surface as `missingLessonIds` by the caller.
  return lessonIds.map((id) => byId.get(id)).filter((l): l is VocabLesson => l !== undefined);
}

interface WordWithLesson extends VocabWord {
  lessonId: string;
}

/** One MC question from `word`, or null if there aren't enough distinct
 *  distractors anywhere in `pool` to build four real options. */
function buildVocabQuestion(
  word: WordWithLesson,
  meaningPool: string[],
  wordPool: string[],
  usedQuestions: ReadonlySet<string>,
): Question | null {
  const wordToMeaning = Math.random() < 0.5;
  if (wordToMeaning) {
    const question = `What does "${word.word}" (${word.reading}) mean?`;
    if (usedQuestions.has(question)) return null;
    const distractors = pickDistractors(word.meaning, meaningPool, 3);
    if (distractors.length < 3) return null;
    const opts = shuffle([word.meaning, ...distractors]);
    return {
      id: 0,
      category: 'vocabulary',
      question,
      options: opts,
      correctIndex: opts.indexOf(word.meaning),
      lessonId: word.lessonId,
    };
  }
  const question = `Which word means "${word.meaning}"?`;
  if (usedQuestions.has(question)) return null;
  const distractors = pickDistractors(word.word, wordPool, 3);
  if (distractors.length < 3) return null;
  const opts = shuffle([word.word, ...distractors]);
  return {
    id: 0,
    category: 'vocabulary',
    question,
    options: opts,
    correctIndex: opts.indexOf(word.word),
    lessonId: word.lessonId,
  };
}

/** Try every word in `lesson`, in random order, until one yields a usable question. */
function coveringVocabQuestion(
  lesson: VocabLesson,
  meaningPool: string[],
  wordPool: string[],
  usedQuestions: ReadonlySet<string>,
): Question | null {
  for (const word of shuffle(lesson.words)) {
    const q = buildVocabQuestion({ ...word, lessonId: lesson.id }, meaningPool, wordPool, usedQuestions);
    if (q) return q;
  }
  return null;
}

async function generateVocabRangeQuestions(lang: string, lessonIds: readonly string[]): Promise<LessonRangeQuestions> {
  const lessons = await fetchVocabLessonsByIds(lang, lessonIds);
  const lessonsById = new Map(lessons.map((l) => [l.id, l]));
  const meaningPool = lessons.flatMap((l) => l.words.map((w) => w.meaning));
  const wordPool = lessons.flatMap((l) => l.words.map((w) => w.word));

  const questions: Question[] = [];
  const coveredLessonIds: string[] = [];
  const missingLessonIds: string[] = [];
  const usedQuestions = new Set<string>();

  // Pass 1: one guaranteed, attributed question per lesson.
  for (const lessonId of lessonIds) {
    const lesson = lessonsById.get(lessonId);
    const q = lesson ? coveringVocabQuestion(lesson, meaningPool, wordPool, usedQuestions) : null;
    if (!q) {
      missingLessonIds.push(lessonId);
      continue;
    }
    questions.push(q);
    usedQuestions.add(q.question);
    coveredLessonIds.push(lessonId);
  }

  // Pass 2: a second question for lessons with more than one word, for
  // depth — still capped and still attributed, never at the expense of
  // pass 1's coverage guarantee.
  for (const lessonId of coveredLessonIds) {
    if (questions.length >= MAX_RANGE_QUESTIONS) break;
    const lesson = lessonsById.get(lessonId)!;
    if (lesson.words.length < 2) continue;
    const q = coveringVocabQuestion(lesson, meaningPool, wordPool, usedQuestions);
    if (q) {
      questions.push(q);
      usedQuestions.add(q.question);
    }
  }

  const shuffled = shuffle(questions).map((q, i) => ({ ...q, id: i }));
  return { questions: shuffled, coveredLessonIds, missingLessonIds };
}

interface QuizWithLesson extends GrammarQuiz {
  lessonId: string;
}

async function fetchGrammarQuizzesByIds(
  lang: string,
  lessonIds: readonly string[],
): Promise<Map<string, QuizWithLesson[]>> {
  const base = import.meta.env.BASE_URL;
  const byLesson = new Map<string, QuizWithLesson[]>();
  const results = await Promise.allSettled(
    lessonIds.map(async (id) => {
      const res = await fetch(`${base}content/grammar/${lang}/${id}.md`);
      if (!res.ok) return { id, quizzes: [] as GrammarQuiz[] };
      const text = await res.text();
      const quizzes: GrammarQuiz[] = [];
      for (const m of text.matchAll(/<!-- quiz:(.*?) -->/g)) {
        try {
          quizzes.push(JSON.parse(m[1]));
        } catch {
          /* skip malformed */
        }
      }
      return { id, quizzes };
    })
  );
  for (const r of results) {
    if (r.status === 'fulfilled') {
      byLesson.set(r.value.id, r.value.quizzes.map((q) => ({ ...q, lessonId: r.value.id })));
    }
  }
  return byLesson;
}

async function generateGrammarRangeQuestions(lang: string, lessonIds: readonly string[]): Promise<LessonRangeQuestions> {
  const byLesson = await fetchGrammarQuizzesByIds(lang, lessonIds);

  const questions: Question[] = [];
  const coveredLessonIds: string[] = [];
  const missingLessonIds: string[] = [];
  const usedByLesson = new Map<string, Set<string>>();

  const pick = (lessonId: string): QuizWithLesson | null => {
    const list = byLesson.get(lessonId);
    if (!list || list.length === 0) return null;
    const used = usedByLesson.get(lessonId) ?? new Set<string>();
    const remaining = list.filter((q) => !used.has(q.question));
    if (remaining.length === 0) return null;
    const [chosen] = pickRandom(remaining, 1);
    used.add(chosen.question);
    usedByLesson.set(lessonId, used);
    return chosen;
  };

  // Pass 1: one guaranteed, attributed question per lesson.
  for (const lessonId of lessonIds) {
    const chosen = pick(lessonId);
    if (!chosen) {
      missingLessonIds.push(lessonId);
      continue;
    }
    questions.push({
      id: 0,
      category: 'grammar',
      question: chosen.question,
      options: chosen.options,
      correctIndex: chosen.answer,
      lessonId,
    });
    coveredLessonIds.push(lessonId);
  }

  // Pass 2: a second question where the lesson has more than one quiz block.
  for (const lessonId of coveredLessonIds) {
    if (questions.length >= MAX_RANGE_QUESTIONS) break;
    const chosen = pick(lessonId);
    if (!chosen) continue;
    questions.push({
      id: 0,
      category: 'grammar',
      question: chosen.question,
      options: chosen.options,
      correctIndex: chosen.answer,
      lessonId,
    });
  }

  const shuffled = shuffle(questions).map((q, i) => ({ ...q, id: i }));
  return { questions: shuffled, coveredLessonIds, missingLessonIds };
}

/**
 * Generates an assessment for testing out of `lessonIds` (an ordered, single
 * -track range within Grammar or Vocabulary — the caller, not this function,
 * is responsible for keeping the two tracks from mixing).
 *
 * `missingLessonIds` in the result is the coverage guarantee surfacing as
 * data: if it's non-empty, at least one lesson in the range couldn't be
 * given an attributable question, and the caller should refuse the test-out
 * attempt for that range rather than silently granting credit for a lesson
 * nobody was actually tested on.
 */
export async function generateLessonRangeQuestions(
  lang: string,
  kind: 'grammar' | 'vocab',
  lessonIds: readonly string[],
): Promise<LessonRangeQuestions> {
  if (lessonIds.length === 0) {
    return { questions: [], coveredLessonIds: [], missingLessonIds: [] };
  }
  return kind === 'grammar'
    ? generateGrammarRangeQuestions(lang, lessonIds)
    : generateVocabRangeQuestions(lang, lessonIds);
}
